---

iserver_hostname: centos77-kvm
iserver_sshkey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDK1zNq5zsVbbN/gLdYqxlb5CROsR1dBNBgRFzzCJUL3ncU2dDHLHWi0L/FafwWt6MQ7vePu7catLDegY2fs1QB0KYvy21fD3+9ONBs7KcFlmuyqjLJ9VAoLWW5Tv3I9eZNgpd9k6CvYphKa1Owq43ye+quQRI4J+2nb7Zhl2WTQ1N2WBwZbmf0ErTHwa+mC7frTRBYh6ddyXp9KRULH89y/6cVpL6uQyFzIr6yWowUbJ8lX3fA9e7RAxkG76X54sMa65oq3Bog04ylJ4n/xZCXO449BZjAZHcJuDcFLXrwIo52t+Q6gIEnXInTiii26/ZWbnzzheggjkpQ77tCg03t christian@Chris-GigaMac.local"

iserver_ubuntu_repos:
  - deb http://archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse
  - deb-src http://archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse
  - deb http://archive.ubuntu.com/ubuntu/ focal-updates main restricted universe multiverse
  - deb-src http://archive.ubuntu.com/ubuntu/ focal-updates main restricted universe multiverse
  - deb http://archive.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
  - deb-src http://archive.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
  - deb http://archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse
  - deb-src http://archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse
  - deb http://archive.canonical.com/ubuntu focal partner
  - deb-src http://archive.canonical.com/ubuntu focal partner

iserver_deb_packages:
  - openssh-server   # needed for Travis testing
  - qemu-guest-agent # needed by packer
  - sudo
  - python-apt       # used by ansible
  - haveged          # prevent vm boot delays
  - net-tools        # includes ifconfig, netstat
  - nano             # set as default editor in .profile
  - psmisc           # includes pstree
  - wget
  - curl
  - lsof
  - lshw
  - ncdu
  - netstat-nat
  - dnsutils
  - pv
  - screen

iserver_rpm_packages:
  - redhat-lsb-core
  - wget
  - curl
  - htop

iserver_centos_enable_epel: true

iserver_domain: home.v-lad.org

iserver_bashrc_user_ubuntu: |
  export PS1="\[\033[1;34m\][\u@\h:\w]$\[\033[0m\] "
  export EDITOR=/usr/bin/vim

iserver_motd_welcome:
  echo "Centos template: $PRETTY_NAME"
